name: Telegram Notification on Push to Main

env:
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

on:
    push:
        branches:
        - main

jobs:
    enviar-mensaje:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout del código
          uses: actions/checkout@v2
    
        - name: Configurar Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
    
        - name: Instalar dependencias
          run: npm install
    
        - name: Ejecutar script
          run: node sendTelegramMessage.js
