name: Despliegue de Notificaciones Automáticas

on:
    push:
        branches:
        - main

jobs:
    send-notification:
        name: Enviar Notificación
        runs-on: ubuntu-latest

        steps:
        - name: Checkout código
          uses: actions/checkout@v2

        - name: Enviar Notificación a Telegram
          run: |
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_CHAT_ID=<ID_DEL_CHAT>

            message="Se realizó un push en la rama main de ${GITHUB_REPOSITORY}"
            url="https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
            data="chat_id=${TELEGRAM_CHAT_ID}&text=${message}"
            
            response=$(curl -s -X POST "${url}?${data}")
            echo "$response"